<a href="https://colab.research.google.com/github/woobin-betty/BDA/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.ndarray([2,3])
a

array([[2.35312988e-315, 0.00000000e+000, 6.80590156e-310],
       [6.80592090e-310, 6.80590147e-310, 6.80592269e-310]])

In [4]:
import numpy as np
a = np.ndarray((3,2), dtype=int)

In [5]:
a = np.ndarray((3,2), int)
a

array([[      480520973,               0],
       [       11664816, 137752958099952],
       [137753386331440,        11664576]])

In [6]:
import numpy as np
a = np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [9]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [10]:
np.array([1,'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [12]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [13]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

In [14]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [15]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [16]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [19]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [20]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [21]:
print( (3-2) / (50-1))

0.02040816326530612


In [22]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [23]:
print( (3-2) / 50)

0.02


In [24]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [25]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [29]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [30]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [31]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b = np.full_like(a, [1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [34]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [35]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [36]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [38]:
b +- a
b

array([0.5, 1.5, 2.5, 3.5])

In [39]:
a@b

np.float64(17.0)

In [40]:
a.dot(b)

np.float64(17.0)

In [41]:
b.dot(a)

np.float64(17.0)

In [42]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

17.0
17.0


In [43]:
import numpy as np

a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [46]:
print(a[3])
print(a[-2])

9
64


In [47]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [48]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [49]:
a[::-2]

array([81, 49, 25,  9,  1])

In [50]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [51]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [52]:
a[2:5] = [-5,-5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [53]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

In [54]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [55]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [56]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [57]:
a[-2,:]

array([18, 19, 20, 21, 22, 23])

In [58]:
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [59]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [60]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [61]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [62]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [63]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [64]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [65]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [67]:
a[2,4]

np.int64(16)

In [68]:
a[2][4]

np.int64(16)

In [69]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [70]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [71]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [72]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [73]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [75]:
a = np.array([3,4,5])
b = np.array([8,7,6])
a + b

array([11, 11, 11])

In [76]:
a = np.array([3,4,5,7])
b = np.array([8,7,6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [77]:
from numpy import arange
x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
y = arange(-1,2)
y

array([-1,  0,  1])

In [79]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [81]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [82]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
y = arange(3, 10, 3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [84]:
# 소수점 이하 자릿수를 2자리로 설정
np.set_printoptions(precision=2)

In [85]:
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [86]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [87]:
from numpy import arange
x = arange(1,4)
x

array([1, 2, 3])

In [89]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [90]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [91]:
x/y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])